### ISSUE TITLE
Support for Solaris

### ISSUE THREAD

**Issue by kildonan5** [blendin/3snake#10]
Does 3snake have support for Solaris (11.4)? When I attempt to execute it I see this error:

    bash-5.0#  ./3snake
    bash: ./3snake: Invalid argument

Some Googling suggests that its an architecture issue (running an "x86 binary on a SPARC machine").

However, when I run file on 3nsake, I see:

    bash-5.0#  file 3snake
    3snake:             ELF 64-bit LSB dynamic lib AMD64 Version 1, position-independent executable, dynamically linked, not stripped, no debugging information available`

And as far as I can tell, Solaris is x64 architecture:

    bash-5.0#  isainfo -v
    64-bit sparcv9 applications
            vis3c vis3b crc32c cbcond pause mont mpmul sha512 sha256
            sha1 md5 camellia kasumi des aes ima hpc vis3 fmaf
            asi_blk_init vis2 vis popc fsmuld div32 mul32
    32-bit sparc applications
            vis3c vis3b crc32c cbcond pause mont mpmul sha512 sha256
            sha1 md5 camellia kasumi des aes ima hpc vis3 fmaf
            asi_blk_init vis2 vis popc v8plus fsmuld div32 mul32

Any suggestions?

**Comment by blendin** [comment]
$200 bounty on this bug for anyone who adds Solaris support.

**Comment by mikeryan** [comment]
Couple things here. First of all a Linux bin won't work on Solaris period. You would need to compile 3snake for Solaris.

Secondly, the approach 3snake currently uses for syscall tracing is the Linux-specific `ptrace` system call. To support Solaris, the guts of the tool would need to be rewritten to use its `Pgrab` interface, and somehow monitor new process creation via `dtruss`. I haven't seen any solid docs on how to do the latter, so if anyone knows please link them on this ticket.

Finally, the Solaris box you're on is Sparc-based, not Intel.
