### ISSUE TITLE
sudo tracing doesn't work on centos 6.2 x64

### ISSUE THREAD

**Issue by artkond** [blendin/3snake#2]
Hey there! Sudo password capture doesn't seem to work on centos 6.2 x64. Older Red Hat based systems are super common on pentests so it would be great if this tool worked on them. Sshd sniffing works.

```
[user1@centos6 root]$ sudo -i
[sudo] password for user1: 
[root@centos6 ~]# whoami
root
[root@centos6 ~]# 
```

No result:
```
[root@centos6 3snake]# ./3snake 
[user1] 8266 sudo -i 	
```

**Comment by blendin** [comment]
Thanks for the report! Will look into this

**Comment by blendin** [comment]
Going on vacation for a week sorry. Will keep working on this when I get back.

**Comment by blendin** [comment]
Have this fixed locally give me a few days of testing.
