### ISSUE TITLE
sshd: Less than 5 character passwords don't capture

### ISSUE THREAD

**Issue by corefx** [blendin/3snake#4]
Hi,
I tested 3snake on Ubuntu 16.04.3 (64 bit) and I noticed that sshd tracing is not capturing the password. Sudo tracing works fine.
![screenshot from 2018-02-11 14-11-31](https://user-images.githubusercontent.com/10615238/36073333-7c519648-0f37-11e8-86d5-7855e6a3766b.png)

**Comment by blendin** [comment]
Hey sorry I'm unable to reproduce this. Could you provide a few more details.
Some other things to note: if the password you are testing with is less than 5 characters it will not capture.

**Comment by corefx** [comment]
Hi,
It was less than 5 characters. I changed the password to a longer one and it works now. It might be a good idea to add support for less than 5 character passwords. Thanks!

**Comment by blendin** [comment]
@corefx should now be fixed. Set the compile time option SHORT_SSH_STRINGS to 1 in config.h before compile and short strings will be traced. If you can confirm before I close that would be great. Will probably close tomorrow if I don't get a response.

**Comment by corefx** [comment]
I can confirm that short passwords are now captured. Thanks!
