### ISSUE TITLE
-o does not account for relative paths, only absolute paths

### ISSUE THREAD

**Issue by tophertimzen** [blendin/3snake#8]
When running 3snake with `-o` giving a relative path, ie `sudo ./3snake -d -o "output.txt"`, no output file is generated. If an absolute path is given, ie `sudo ./3snake -d -o "/tmp/output.txt"` then one is. This makes me assume that 3snake is not accounting for its path when it is ran. I suggest one of the following

1. Change the `-h` and `README` to mention 3snake needing an absolute path
1. Change 3snake functionality to account for relative paths when outputting to a file.

**Comment by altmas5** [comment]
I couldn't make it write to file (maybe I'm lacking of some ptrace related software or configuration), but I can confirm that the file is not created when the full path is not specified.

**Comment by altmas5** [comment]
I think any of the would be ok, document it better or change the functionality for daemon mode.
